### ISSUE TITLE
failed to locate formatting script

### ISSUE THREAD

**Issue by warner** [glyph/python-docstring-mode#23]
The first time I installed this (via melpa), the mode wasn't able to find the embedded `docstring_wrap.py` file. Using M-q to reformat docstrings cause the whole comment to be replaced by a "couldn't find file" error string.

I wound up setting it manually with the (built-in, thank you!) `python-docstring-script` variable, but it looks like it's supposed to be able to find it on its own. I'll try to debug this at some point and submit a patch.. just filing the issue now in case I forget.

**Comment by glyph** [comment]
Thanks for the report.

**Comment by warner** [comment]
Nevermind, I had a leftover symlink-based install still present, so `load-file-name` was pointing into the wrong directory. The code that sets `python-docstring-script` is working as intended. PEBCAK.
