### ISSUE TITLE
Don't reflow doctest blocks in epytext

### ISSUE THREAD

**Issue by wecassidy** [glyph/python-docstring-mode#25]
When I hit <kbd>M-q</kbd>, doctest blocks are reflowed when the should be left alone. For example,
```
"""
Example docstring.

    >>> print("Hi!")
    >>> print("This is a doctest block.")

And some more text.
"""
```
becomes 
```
"""
Example docstring.

>>> print("Hi!") >>> print("This is a doctest block")

And some more text.
"""
```

The doctest block (in the middle) lost its indentation and the two lines were placed one after the other.

**Comment by glyph** [comment]
Does epytext actually recognize these as blocks? Hmm.

**Comment by wecassidy** [comment]
Not actually an issue. I was formatting the blocks wrong. The paragraph before the block is supposed to close with two colons. When they're formatted correctly, the plugin indents as expected.

**Comment by glyph** [comment]
Thanks for following up! That is indeed how I thought it worked :)
