### ISSUE TITLE
if I switch to python 3 I get an extra newline before @-fields

### ISSUE THREAD

**Issue by glyph** [glyph/python-docstring-mode#26]
??? I have no idea why this is.

**Comment by nighthawk9** [comment]
I've been trying to solve this problem for an hour now, and I believe it has to do with tag checking and the output of new lines.

I don't understand the entire code base, as it's quite confusing, but it may be a start to look at the two problem locations (Line 517 and Line 237) and not adding a newline in based on the text its writing.

**Comment by glyph** [comment]
I believe this (along with a switch to python 3) is fixed in 0d2f783f5a868ded8a37aa5881f8952aa36b053f.
