### ISSUE TITLE
Problems locating `docstring_wrap.py`

### ISSUE THREAD

**Issue by berhoel** [glyph/python-docstring-mode#9]
I installed „`python-docstring-mode`“ from melpa. The installed module was unable to locate „`docstring_wrap.py`“. I fixed this by rewriting the `defvar` for `python-docstring-script`:

``` lisp
(defvar python-docstring-script
  (concat (file-name-directory (locate-library "python-docstring"))
          "docstring_wrap.py")
  "The location of the docstring_wrap.py script.")
```

**Comment by berhoel** [comment]
I still have the problem with the latest install from melpa.

**Comment by berhoel** [comment]
Added pull request #13

**Comment by berhoel** [comment]
Removed pull request #13, it is a duplicate of #4.

**Comment by glyph** [comment]
#4 has been merged so hopefully this is fixed.
